#include "zcommon.acs"
#library "FLGLIGHT"

Script 900 (int lowlight, int highlight)
{
    // Set the beginning sector tag.
    int i;
    if (i == 0) i = 100;

    //Dim the current sector.
    Light_Fade (i, lowlight, 16);

    // Get the next sector tag.
    i++;

    // Wrap around to beginning sector.
    if (i > 115) i = 100;

    // Set the next sector to bright.
    Light_ChangeToValue (i, highlight);
        
    Delay (2);
    Restart;
}